# =============================================================================
# REPRODUCIBILITY TEST -- STEP 1: generate a FRESH, INDEPENDENT 30-subject dataset from the
# CORRECTED model (denosumab_QSS_TMDD_v2.R, commit 8fb40db).
#
# Does NOT reuse simulated_denosumab_data_v2.csv (generated by the buggy model).
# Model block below is copied VERBATIM from the CURRENT denosumab_QSS_TMDD_v2.R
# Stage 3 (L147-170, post-fix) -- nothing altered.
#
# Output: simulated_denosumab_data_v2_corrected_repro.csv
# =============================================================================
suppressPackageStartupMessages({library(rxode2); library(dplyr)})

set.seed(2025)

true_params <- list(
  ka = 0.0078, Vc = 1.58, Vp = 6.06, CL = 0.006, Q = 0.20, kint = 0.022,
  Kss = 1.56, ksyn = 0.01, R0 = 15.23
)
true_params$kdeg <- true_params$ksyn / true_params$R0

cv_to_omega2 <- function(cv_pct) log(1 + (cv_pct / 100)^2)
true_omega2 <- list(
  ka = cv_to_omega2(56.57), Vc = cv_to_omega2(61.69), Vp = cv_to_omega2(15.55),
  kint = cv_to_omega2(7.88), Kss = cv_to_omega2(58.12), ksyn = cv_to_omega2(22.46),
  R0 = cv_to_omega2(158.3), CL = cv_to_omega2(26.39), Q = cv_to_omega2(295.99)
)
true_sigma_add  <- 0.72
true_sigma_prop <- 0.07

MW_kDa <- 147; dose_mg <- 60
dose_nmol <- (dose_mg * 1e6) / (MW_kDa * 1e3)

# REPRO: 30 subjects, SAME protocol as the pilot, but a DIFFERENT generation seed
# (2025 instead of 42) so this is an independent random draw, not a copy.
n_subjects <- 30
month_h <- 30.44 * 24
sample_offsets_h <- c(12, 24, 72, 168, 336, 720, 1440, 2160)
dose_times_h <- c(0, 6, 12) * month_h

# ---- verbatim copy of the CORRECTED model block (denosumab_QSS_TMDD_v2.R, commit 8fb40db) ----
qss_model_rxode <- rxode2({
  ka    <- exp(lka + eta_ka)
  Vc    <- exp(lVc + eta_Vc)
  Vp    <- exp(lVp + eta_Vp)
  CL    <- exp(lCL + eta_CL)
  Q     <- exp(lQ  + eta_Q)
  kint  <- exp(lkint + eta_kint)
  Kss   <- exp(lKss + eta_Kss)
  ksyn  <- exp(lksyn + eta_ksyn)
  R0    <- exp(lR0 + eta_R0)
  kdeg  <- ksyn / R0

  disc  <- (Ctot - Rtot - Kss)^2 + 4 * Kss * Ctot
  discP <- max(disc, 0)
  C     <- 0.5 * ((Ctot - Rtot - Kss) + sqrt(discP))
  Cfree <- max(C, 0)
  RC    <- Ctot - Cfree

  d/dt(depot) <- -ka * depot
  d/dt(Ctot)  <- (ka * depot) / Vc - (CL / Vc) * Cfree - (Q / Vc) * Cfree +
                 (Q / Vc) * Cp - kint * RC
  d/dt(Cp)    <- (Q / Vp) * Cfree - (Q / Vp) * Cp
  d/dt(Rtot)  <- ksyn - kdeg * (Rtot - RC) - kint * RC
})

sim_params <- data.frame(
  id       = 1:n_subjects,
  eta_ka   = rnorm(n_subjects, 0, sqrt(true_omega2$ka)),
  eta_Vc   = rnorm(n_subjects, 0, sqrt(true_omega2$Vc)),
  eta_Vp   = rnorm(n_subjects, 0, sqrt(true_omega2$Vp)),
  eta_CL   = rnorm(n_subjects, 0, sqrt(true_omega2$CL)),
  eta_Q    = rnorm(n_subjects, 0, sqrt(true_omega2$Q)),
  eta_kint = rnorm(n_subjects, 0, sqrt(true_omega2$kint)),
  eta_Kss  = rnorm(n_subjects, 0, sqrt(true_omega2$Kss)),
  eta_ksyn = rnorm(n_subjects, 0, sqrt(true_omega2$ksyn)),
  eta_R0   = rnorm(n_subjects, 0, sqrt(true_omega2$R0))
)

theta <- log(c(
  true_params$ka, true_params$Vc, true_params$Vp, true_params$CL,
  true_params$Q, true_params$kint, true_params$Kss,
  true_params$ksyn, true_params$R0
))
names(theta) <- c("lka","lVc","lVp","lCL","lQ","lkint","lKss","lksyn","lR0")

sim_results <- list()
for (i in 1:n_subjects) {
  p    <- sim_params[i, ]
  R0_i <- exp(theta["lR0"] + p$eta_R0)

  ev <- eventTable()
  for (dt in dose_times_h) {
    ev$add.dosing(dose = dose_nmol, start.time = dt, dosing.to = "depot")
  }
  samp_times <- sort(unique(as.vector(outer(dose_times_h, sample_offsets_h, "+"))))
  samp_times <- samp_times[samp_times <= max(dose_times_h) + max(sample_offsets_h)]
  ev$add.sampling(samp_times)

  inits <- c(depot = 0, Ctot = 0, Cp = 0, Rtot = as.numeric(R0_i))

  subj_params <- c(theta,
                   eta_ka = p$eta_ka, eta_Vc = p$eta_Vc, eta_Vp = p$eta_Vp,
                   eta_CL = p$eta_CL, eta_Q = p$eta_Q, eta_kint = p$eta_kint,
                   eta_Kss = p$eta_Kss, eta_ksyn = p$eta_ksyn, eta_R0 = p$eta_R0)

  sol           <- rxSolve(qss_model_rxode, subj_params, ev, inits = inits)
  sol_df        <- as.data.frame(sol)
  sol_df$ID     <- i
  sim_results[[i]] <- sol_df
}

sim_all <- bind_rows(sim_results)

sim_all <- sim_all %>%
  mutate(
    IPRED    = Ctot,
    err_add  = rnorm(n(), 0, true_sigma_add),
    err_prop = rnorm(n(), 0, true_sigma_prop),
    DV       = IPRED * (1 + err_prop) + err_add
  )

cat("Simulated dataset:", nrow(sim_all), "records across", n_subjects, "subjects\n")
cat(sprintf("  negative DV values: %d  (should be 0)\n", sum(sim_all$DV < 0)))

obs_rows <- sim_all %>%
  filter(time %in% unlist(lapply(dose_times_h, function(dt) dt + sample_offsets_h))) %>%
  transmute(ID, TIME = time, AMT = 0, DV = DV, EVID = 0, CMT = 2)

dose_rows <- expand.grid(ID = 1:n_subjects, TIME = dose_times_h) %>%
  transmute(ID, TIME, AMT = dose_nmol, DV = 0, EVID = 1, CMT = 1)

pk_data_pilot <- bind_rows(obs_rows, dose_rows) %>%
  arrange(ID, TIME, desc(EVID))

write.csv(pk_data_pilot, "simulated_denosumab_data_v2_corrected_repro.csv", row.names = FALSE)
cat("Saved: simulated_denosumab_data_v2_corrected_repro.csv\n")
cat("Rows:", nrow(pk_data_pilot),
    " (obs:", sum(pk_data_pilot$EVID == 0), " dose:", sum(pk_data_pilot$EVID == 1), ")\n")
cat("Subjects:", length(unique(pk_data_pilot$ID)), "\n")
